# Generated by Django 5.2 on 2026-03-11 16:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('direction', models.CharField(max_length=31)),
                ('text', models.CharField(max_length=127)),
                ('translation', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('direction', models.CharField(max_length=31)),
                ('text', models.CharField(max_length=127)),
                ('translation', tinymce.models.HTMLField()),
                ('redirect_to', models.URLField(blank=True, null=True)),
                ('stress', models.CharField(blank=True, help_text='Націск', max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Словы',
                'unique_together': {('external_id', 'direction')},
            },
        ),
    ]
