# Generated by Django 5.2 on 2026-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(db_index=True, max_length=127),
        ),
    ]
