# Generated by Django 4.2.5 on 2023-10-05 08:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('external_id', 'direction')},
        ),
    ]
