# Generated by Django 5.2 on 2026-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_word_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='Слова без націску (ключ пошуку)', max_length=127)),
                ('lemma', models.CharField(help_text='Слова з націскам', max_length=127)),
                ('table_name', models.CharField(blank=True, help_text='Частка мовы', max_length=31, null=True)),
                ('source_pdg_id', models.BigIntegerField(blank=True, help_text='ID парадыгмы ў GrammarDB', null=True, unique=True)),
                ('rows', models.JSONField(help_text='Радкі табліцы скланення/спражэння')),
            ],
            options={
                'verbose_name': 'Слова з націскам',
                'verbose_name_plural': 'Словы з націскам',
            },
        ),
    ]
