# Generated by Django 5.0 on 2025-01-05 11:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_word_translation_alter_word_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('direction', models.CharField(max_length=31)),
                ('text', models.CharField(max_length=127)),
                ('translation', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'translations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Слова', 'verbose_name_plural': 'Словы'},
        ),
        migrations.AddField(
            model_name='word',
            name='redirect_to',
            field=models.URLField(blank=True, null=True),
        ),
    ]
