# Generated by Django 5.1.4 on 2025-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_translation_alter_word_options_word_redirect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='stress',
            field=models.CharField(blank=True, help_text='Націск', max_length=127, null=True),
        ),
    ]
